Rails.application.config.to_prepare do

  	CountyLookup.data = [
     
      {:id => 1, :name => "Fairfield"},
      {:id => 2, :name => "Hartford"},
      {:id => 3, :name => "Litchfield"},
      {:id => 4, :name => "Middlesex"},
      {:id => 5, :name => "New Haven"},
      {:id => 6, :name => "New London"},
      {:id => 7, :name => "Tolland"},
      {:id => 8, :name => "Windham"}  
  	]

  	TownLookup.data = [

	  {:id =>	1,	 :name =>	"Andover",		:county_lookup_id =>	7},
	  {:id =>	2,	 :name =>	"Ansonia",		:county_lookup_id =>	5},
	  {:id =>	3,	 :name =>	"Ashford",		:county_lookup_id =>	8},
	  {:id =>	4,	 :name =>	"Avon",		:county_lookup_id =>	2},
	  {:id =>	5,	 :name =>	"Barkhamsted",	:county_lookup_id =>	3},
	  {:id =>	6,	 :name =>	"Beacon Falls",	:county_lookup_id =>	5},
	  {:id =>	7,	 :name =>	"Berlin",		:county_lookup_id =>	2},
	  {:id =>	8,	 :name =>	"Bethany",		:county_lookup_id =>	5},
	  {:id =>	9,	 :name =>	"Bethel",		:county_lookup_id =>	1},
	  {:id =>	10,	 :name =>	"Bethlehem",	:county_lookup_id =>	3},
	  {:id =>	11,	 :name =>	"Bloomfield",	:county_lookup_id =>	2},
	  {:id =>	12,	 :name =>	"Bolton",		:county_lookup_id =>	7},
	  {:id =>	13,	 :name =>	"Bozrah",		:county_lookup_id =>	6},
	  {:id =>	14,	 :name =>	"Branford",		:county_lookup_id =>	5},
	  {:id =>	15,	 :name =>	"Bridgeport",	:county_lookup_id =>	1},
	  {:id =>	16,	 :name =>	"Bridgewater",	:county_lookup_id =>	3},
	  {:id =>	17,	 :name =>	"Bristol",		:county_lookup_id =>	2},
	  {:id =>	18,	 :name =>	"Brookfield",	:county_lookup_id =>	1},
	  {:id =>	19,	 :name =>	"Brooklyn",		:county_lookup_id =>	8},
	  {:id =>	20,	 :name =>	"Burlington",	:county_lookup_id =>	2},
	  {:id =>	21,	 :name =>	"Canaan",		:county_lookup_id =>	3},
	  {:id =>	22,	 :name =>	"Canterbury",	:county_lookup_id =>	8},
	  {:id =>	23,	 :name =>	"Canton",		:county_lookup_id =>	2},
	  {:id =>	24,	 :name =>	"Chaplin",		:county_lookup_id =>	8},
	  {:id =>	25,	 :name =>	"Cheshire",		:county_lookup_id =>	5},
	  {:id =>	26,	 :name =>	"Chester",		:county_lookup_id =>	4},
	  {:id =>	27,	 :name =>	"Clinton",		:county_lookup_id =>	4},
	  {:id =>	28,	 :name =>	"Colchester",	:county_lookup_id =>	6},
	  {:id =>	29,	 :name =>	"Colebrook",	:county_lookup_id =>	3},
	  {:id =>	30,	 :name =>	"Columbia",		:county_lookup_id =>	7},
	  {:id =>	31,	 :name =>	"Cornwall",		:county_lookup_id =>	3},
	  {:id =>	32,	 :name =>	"Coventry",		:county_lookup_id =>	7},
	  {:id =>	33,	 :name =>	"Cromwell",		:county_lookup_id =>	4},
	  {:id =>	34,	 :name =>	"Danbury",		:county_lookup_id =>	1},
	  {:id =>	35,	 :name =>	"Darien",		:county_lookup_id =>	1},
	  {:id =>	36,	 :name =>	"Deep River",	:county_lookup_id =>	4},
	  {:id =>	37,	 :name =>	"Derby",		:county_lookup_id =>	5},
	  {:id =>	38,	 :name =>	"Durham",		:county_lookup_id =>	4},
	  {:id =>	39,	 :name =>	"East Granby",	:county_lookup_id =>	2},
	  {:id =>	40,	 :name =>	"East Haddam",	:county_lookup_id =>	4},
	  {:id =>	41,	 :name =>	"East Hampton",	:county_lookup_id =>	4},
	  {:id =>	42,	 :name =>	"East Hartford",:county_lookup_id =>	2},
	  {:id =>	43,	 :name =>	"East Haven",	:county_lookup_id =>	5},
	  {:id =>	44,	 :name =>	"East Lyme",	:county_lookup_id =>	6},
	  {:id =>	45,	 :name =>	"East Windsor",	:county_lookup_id =>	2},
	  {:id =>	46,	 :name =>	"Eastford",		:county_lookup_id =>	8},
	  {:id =>	47,	 :name =>	"Easton",		:county_lookup_id =>	1},
	  {:id =>	48,	 :name =>	"Ellington",	:county_lookup_id =>	7},
	  {:id =>	49,	 :name =>	"Enfield",		:county_lookup_id =>	2},
	  {:id =>	50,	 :name =>	"Essex",		:county_lookup_id =>	4},
	  {:id =>	51,	 :name =>	"Fairfield",	:county_lookup_id =>	1},
	  {:id =>	52,	 :name =>	"Farmington",	:county_lookup_id =>	2},
	  {:id =>	53,	 :name =>	"Franklin",		:county_lookup_id =>	6},
	  {:id =>	54,	 :name =>	"Glastonbury",	:county_lookup_id =>	2},
	  {:id =>	55,	 :name =>	"Goshen",		:county_lookup_id =>	3},
	  {:id =>	56,	 :name =>	"Granby",		:county_lookup_id =>	2},
	  {:id =>	57,	 :name =>	"Greenwich",	:county_lookup_id =>	1},
	  {:id =>	58,	 :name =>	"Griswold",		:county_lookup_id =>	6},
	  {:id =>	59,	 :name =>	"Groton",		:county_lookup_id =>	6},
	  {:id =>	60,	 :name =>	"Guilford",		:county_lookup_id =>	5},
	  {:id =>	61,	 :name =>	"Haddam",		:county_lookup_id =>	4},
	  {:id =>	62,	 :name =>	"Hamden",		:county_lookup_id =>	5},
	  {:id =>	63,	 :name =>	"Hampton",		:county_lookup_id =>	8},
	  {:id =>	64,  :name =>	"Hartford",		:county_lookup_id =>	2},
	  {:id =>	65,  :name =>	"Hartland",		:county_lookup_id =>	2},
	  {:id =>	66,  :name =>	"Harwinton",	:county_lookup_id =>	3},
	  {:id =>	67,  :name =>	"Hebron",		:county_lookup_id =>	7},
	  {:id =>	68,  :name =>	"Kent",			:county_lookup_id =>	3},
	  {:id =>	69,  :name =>	"Killingly",	:county_lookup_id =>	8},
	  {:id =>	70,  :name =>	"Killingworth",	:county_lookup_id =>	4},
	  {:id =>	71,  :name =>	"Lebanon",		:county_lookup_id =>	6},
	  {:id =>	72,  :name =>	"Ledyard",		:county_lookup_id =>	6},
	  {:id =>	73,  :name =>	"Lisbon",		:county_lookup_id =>	6},
	  {:id =>	74,  :name =>	"Litchfield",	:county_lookup_id =>	3},
	  {:id =>	75,  :name =>	"Lyme",			:county_lookup_id =>	6},
	  {:id =>	76,  :name =>	"Madison",		:county_lookup_id =>	5},
	  {:id =>	77,  :name =>	"Manchester",	:county_lookup_id =>	2},
	  {:id =>	78,  :name =>	"Mansfield",	:county_lookup_id =>	7},
	  {:id =>	79,  :name =>	"Marlborough",	:county_lookup_id =>	2},
	  {:id =>	80,  :name =>	"Meriden",		:county_lookup_id =>	5},
	  {:id =>	81,  :name =>	"Middlebury",	:county_lookup_id =>	5},
	  {:id =>	82,  :name =>	"Middlefield",	:county_lookup_id =>	4},
	  {:id =>	83,  :name =>	"Middletown",	:county_lookup_id =>	4},
	  {:id =>	84,  :name =>	"Milford",		:county_lookup_id =>	5},
	  {:id =>	85,  :name =>	"Monroe",		:county_lookup_id =>	1},
	  {:id =>	86,  :name =>	"Montville",	:county_lookup_id =>	6},
	  {:id =>	87,  :name =>	"Morris",		:county_lookup_id =>	3},
	  {:id =>	88,  :name =>	"Naugatuck",	:county_lookup_id =>	5},
	  {:id =>	89,  :name =>	"New Britain",	:county_lookup_id =>	2},
	  {:id =>	90,  :name =>	"New Canaan",	:county_lookup_id =>	1},
	  {:id =>	91,  :name =>	"New Fairfield",:county_lookup_id =>	1},
	  {:id =>	92,  :name =>	"New Hartford",	:county_lookup_id =>	3},
	  {:id =>	93,  :name =>	"New Haven",	:county_lookup_id =>	5},
	  {:id =>	94,  :name =>	"New London",	:county_lookup_id =>	6},
	  {:id =>	95,  :name =>	"New Milford",	:county_lookup_id =>	3},
	  {:id =>	96,	 :name =>	"Newington",	:county_lookup_id =>	2},
	  {:id =>	97,	 :name =>	"Newtown",		:county_lookup_id =>	1},
	  {:id =>	98,	 :name =>	"Norfolk",		:county_lookup_id =>	3},
	  {:id =>	99,	 :name =>	"North Branford",:county_lookup_id =>	5},
	  {:id =>	100, :name =>	"North Canaan",	:county_lookup_id =>	3},
	  {:id =>	101, :name =>	"North Haven",	:county_lookup_id =>	5},
	  {:id =>	102, :name =>	"North Stonington", :county_lookup_id =>6}	,
	  {:id =>	103, :name =>	"Norwalk",		:county_lookup_id =>	1},
	  {:id =>	104, :name =>	"Norwich",		:county_lookup_id =>	6},
	  {:id =>	105, :name =>	"Old Lyme",		:county_lookup_id =>	6},
	  {:id =>	106, :name =>	"Old Saybrook",	:county_lookup_id =>	4},
	  {:id =>	107, :name =>	"Orange",		:county_lookup_id =>	5},
	  {:id =>	108, :name =>	"Oxford",		:county_lookup_id =>	5},
	  {:id =>	109, :name =>	"Plainfield",	:county_lookup_id =>	8},
	  {:id =>	110, :name =>	"Plainville",	:county_lookup_id =>	2},
	  {:id =>	111, :name =>	"Plymouth",		:county_lookup_id =>	3},
	  {:id =>	112, :name =>	"Pomfret",		:county_lookup_id =>	8},
	  {:id =>	113, :name =>	"Portland",		:county_lookup_id =>	4},
	  {:id =>	114, :name =>	"Preston",		:county_lookup_id =>	6},
	  {:id =>	115, :name =>	"Prospect",		:county_lookup_id =>	5},
	  {:id =>	116, :name =>	"Putnam",		:county_lookup_id =>	8},
	  {:id =>	117, :name =>	"Redding",		:county_lookup_id =>	1},
	  {:id =>	118, :name =>	"Ridgefield",	:county_lookup_id =>	1},
	  {:id =>	119, :name =>	"Rocky Hill",	:county_lookup_id =>	2},
	  {:id =>	120, :name =>	"Roxbury",		:county_lookup_id =>	3},
	  {:id =>	121, :name =>	"Salem",		:county_lookup_id =>	6},
	  {:id =>	122, :name =>	"Salisbury",	:county_lookup_id =>	3},
	  {:id =>	123, :name =>	"Scotland",		:county_lookup_id =>	8},
	  {:id =>	124, :name =>	"Seymour",		:county_lookup_id =>	5},
	  {:id =>	125, :name =>	"Sharon",		:county_lookup_id =>	3},
	  {:id =>	126, :name =>	"Shelton",		:county_lookup_id =>	1},
	  {:id =>	127, :name =>	"Sherman",		:county_lookup_id =>	1},
	  {:id =>	128, :name =>	"Simsbury",		:county_lookup_id =>	2},
	  {:id =>	129, :name =>	"Somers",		:county_lookup_id =>	7},
	  {:id =>	130, :name =>	"South Windsor",:county_lookup_id =>	2},
	  {:id =>	131, :name =>	"Southbury",	:county_lookup_id =>	5},
	  {:id =>	132, :name =>	"Southington",	:county_lookup_id =>	2},
	  {:id =>	133, :name =>	"Sprague",		:county_lookup_id =>	6},
	  {:id =>	134, :name =>	"Stafford",		:county_lookup_id =>	7},
	  {:id =>	135, :name =>	"Stamford",		:county_lookup_id =>	1},
	  {:id =>	136, :name =>	"Sterling",		:county_lookup_id =>	8},
	  {:id =>	137, :name =>	"Stonington",	:county_lookup_id =>	6},
	  {:id =>	138, :name =>	"Stratford",	:county_lookup_id =>	1},
	  {:id =>	139, :name =>	"Suffield",		:county_lookup_id =>	2},
	  {:id =>	140, :name =>	"Thomaston",	:county_lookup_id =>	3},
	  {:id =>	141, :name =>	"Thompson",		:county_lookup_id =>	8},
	  {:id =>	142, :name =>	"Tolland",		:county_lookup_id =>	7},
	  {:id =>	143, :name =>	"Torrington",	:county_lookup_id =>	3},
	  {:id =>	144, :name =>	"Trumbull",		:county_lookup_id =>	1},
	  {:id =>	145, :name =>	"Union",		:county_lookup_id =>	7},
	  {:id =>	146, :name =>	"Vernon",		:county_lookup_id =>	7},
	  {:id =>	147, :name =>	"Voluntown",	:county_lookup_id =>	6},
	  {:id =>	148, :name =>	"Wallingford",	:county_lookup_id =>	5},
	  {:id =>	149, :name =>	"Warren",		:county_lookup_id =>	3},
	  {:id =>	150, :name =>	"Washington",	:county_lookup_id =>	3},
	  {:id =>	151, :name =>	"Waterbury",	:county_lookup_id =>	5},
	  {:id =>	152, :name =>	"Waterford",	:county_lookup_id =>	6},
	  {:id =>	153, :name =>	"Watertown",	:county_lookup_id =>	3},
	  {:id =>	154, :name =>	"West Hartford",:county_lookup_id =>	2},
	  {:id =>	155, :name =>	"West Haven",	:county_lookup_id =>	5},
	  {:id =>	156, :name =>	"Westbrok",		:county_lookup_id =>	4},
	  {:id =>	157, :name =>	"Weston",		:county_lookup_id =>	1},
	  {:id =>	158, :name =>	"Westport",		:county_lookup_id =>	1},
	  {:id =>	159, :name =>	"Wethersfield",	:county_lookup_id =>	2},
	  {:id =>	160, :name =>	"Willington",	:county_lookup_id =>	7},
	  {:id =>	161, :name =>	"Wilton",		:county_lookup_id =>	1},
	  {:id =>	162, :name =>	"Winchester",	:county_lookup_id =>	3},
	  {:id =>	163, :name =>	"Windham",		:county_lookup_id =>	8},
	  {:id =>	164, :name =>	"Windsor",		:county_lookup_id =>	2},
	  {:id =>	165, :name =>	"Windsor Locks",:county_lookup_id =>	2},
	  {:id =>	166, :name =>	"Wolcott",		:county_lookup_id =>	5},
	  {:id =>	167, :name =>	"Woodbridge",	:county_lookup_id =>	5},
	  {:id =>	168, :name =>	"Woodbury"	,	:county_lookup_id =>	3},
	  {:id =>	169, :name =>	"Woodstock"	,	:county_lookup_id =>	8}	

  	]

  	AgeGroupLookup.data = [
     
      {:id => "0-9",   :name => "0-9"},
      {:id => "10-19", :name => "10-19"},
      {:id => "20-29", :name => "20-29"},
      {:id => "30-39", :name => "30-39"},
      {:id => "40-49", :name => "40-49"},
      {:id => "50-59", :name => "50-59"},
      {:id => "60-69", :name => "60-69"},
      {:id => "70-79", :name => "70-79"},
      {:id => "80 and older", :name => "80 and older"}  
  	] 

  	EthnicCaseLookup.data = [
     
      {:id => "Hispanic",   							:name => "Hispanic"},
      {:id => "NH American Indian or Alaskan Native", 	:name => "American Indian or Alaskan Native"},
      {:id => "NH Asian or Pacific Islander", 			:name => "Asian or Pacific Islander"},
      {:id => "NH Black", 								:name => "Black"},
      {:id => "NH Multiracial", 						:name => "Multiracial"},
      {:id => "NH Other", 								:name => "Other"},
      {:id => "NH White", 								:name => "White"},
      {:id => "Unknown", 								:name => "Unknown"}
  	]   	 	


end


